[package]
name = "propositional-logic-rs"
version = "0.1.0"
edition = "2021"
author = "Anthony Rubick"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cli-table = "0.4"
